---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener-container
        image: ghcr.io/irfan-1117/url-shortener:v1 # Name of the secret
        ports:
        - containerPort: 9090


---  
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: NodePort


