apiVersion: apps/v1
kind: Deployment
metadata:
    name: short-url
spec:
    selector:
        matchLabels:
            app: short-url
    replicas: 2
    template:
        metadata:
            labels:
                app: short-url
        spec:
            containers:
                - name: short-url-container
                  imagePullPolicy: Never
                  image: ghcr.io/irfan-1117/url-shortener:v1
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
    name: short-url-service
spec:
    type: NodePort
    selector:
        app: short-url
    ports:
        - port: 9090
          targetPort: 9090
